import Head from 'next/head'
import {useRouter} from 'next/router';
import styles from '../../styles/Home.module.css'
import { useState, useEffect} from 'react'
import AppContainer from '../../components/AppContainer';
import FlowLoader from '../../components/FlowLoader';
import { currentDomain } from '../../const';
import Footer from '../../components/FruitiionFooter';
import isScreenMobile from '../../functions/isScreenMobile';


export default function Profile() {
  const router = useRouter()

  const [isLoading, setIsLoading] = useState(false)
  const [user, setUser] = useState()
  



  const initializeBilling = async () => {
    setIsLoading(true)

    const initializeBillingResponse  = await fetch(`${currentDomain}/api/initializeBilling`)
    const initializeBillingData = await initializeBillingResponse.json()

    if (initializeBillingData.result == 'unauthorized') {
      router.push('/app/offerings')
      return
    }

    if (initializeBillingData.result == "success" ) {
      const { sponsors, investors, assetsUnderManagement, totalRaised, user} = initializeBillingData
      setUser(user)
    }

    setIsLoading(false)
  }


  useEffect(() => {
    const handleResize = () => {
      if (isScreenMobile(window)) {
        router.push('/mobileMessage')
      }
    }
    window.addEventListener("resize", handleResize)
    handleResize()
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Fruitiion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fruitiionIcon.svg" />
      </Head>
      <AppContainer
        userType='sponsor'
        activeSection='billing'
        secondRowContnet={
            <>
              <div className={styles.secondAppSpacer}/>
              
            </>
        }
        appContent={
            <>
            <div className={styles.billingContainer}>
              <div className={styles.billingSection}>
                <a className={styles.planTitle}>Base Plan</a>
                <a className={styles.planName}>Early Bird</a>
                <a className={styles.planPrice}>$0/mo</a>
                <button className={styles.editBillingButton}>Edit</button>
                <br />
                <a className={styles.planTitle}>Number of active sponsor users</a>
                <a className={styles.planName}>2</a>
                <a className={styles.planPrice}>$0/mo</a>
              </div>
              <div className={styles.billingSection}>
                <a className={styles.planTitle}>Payment Method</a>
                <a className={styles.planName}>****-****-****-1234</a>
                <a className={styles.planPrice}>Bank Account</a>
                <button className={styles.editBillingButton}>Edit</button>
              </div>
              
            </div>
            
            </>
        }
      />
      {
        isLoading ?
        <FlowLoader />:
        null
      }
      
      <Footer />
    </div>
  )
}
