import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import {useRouter} from 'next/router';
import styles from '../styles/Home.module.css'
import { currentDomain } from '../const';
import Footer from '../components/FruitiionFooter';



export default function InvestorReminder() {


  const router = useRouter()
  
  const logout = async () => {
    const logoutResponse = await fetch(`${currentDomain}/api/logout`, {
        method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            test: "logged out"
          })
      })
      const logoutData = await logoutResponse.json()
      router.push('/')
}
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Fruitiion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fruitiionIcon.svg" />
      </Head>
      <div className={styles.registrationContainer}>
        <div className={styles.registrationComponentsContainer}>
          <Image alt='Fruitiion logo' className={styles.registrationLogo} src='/fruitiionBannerBlack.svg' width={303} height={106} />
          <div className={styles.registrationStepContainer}>
              <h3 className={styles.intstructionHeader}>YOU MUST BE AN INVESTOR TO INVEST</h3>
              <br />
              <p className={styles.instructionText}>You are not currently logged in as an investor. Please logout and either login as an investor or sign up.</p>
              <br />
              <button className={styles.registrationProgressButton} onClick={() => logout()}>LOGOUT</button>
            </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
