import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from 'next/router';
import styles from '../styles/Home.module.css'
import LoginInput from '../components/LoginInput'
import { useState, useEffect } from 'react'
import FlowLoader from '../components/FlowLoader';
import { currentDomain } from '../const';
import Footer from '../components/FruitiionFooter';
import isScreenMobile from '../functions/isScreenMobile';

export default function Home() {
  const router = useRouter()

  const [showPassword,setShowPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [userType, setUserType] = useState("sponsor")
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [errorMessage, setErrorMessage] = useState("")



  const sponsorLogin = async () => {
    setIsLoading(true)
    const loginResponse = await fetch(`${currentDomain}/api/sponsorLogin`, {
      method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: email,
          password: password
        })
    })
    const loginData = await loginResponse.json()

    if (loginData.result == "success") {
      router.push('/app/deals')
    } else {
      setErrorMessage(loginData.result)
    }
    setIsLoading(false)
  }


  const forgotPassword = async () => {
    setIsLoading(true)
    if (email ==  "") {
      setErrorMessage("Please provide your email.")
      setIsLoading(false)
      return
    }
    setErrorMessage("If your account exist, an email with password reset instructions will be sent shortly")
    const forgotPasswordResponse = await fetch(`${currentDomain}/api/forgotPassword`, {
      method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: email,
          userType: userType
        })
    })
    const forgotPasswordData = await forgotPasswordResponse.json()
    console.log(forgotPasswordData.result)
    setIsLoading(false)
  }



  useEffect(() => {
    const handleResize = () => {
      if (!isScreenMobile(window)) {
        router.push('/')
      }
    }
    window.addEventListener("resize", handleResize)
    handleResize()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Fruitiion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fruitiionIcon.svg" />
      </Head>
      <div className={styles.loginContainer}>
        <div className={styles.loginComponentsContainer}>
          <Image alt='Fruitiion login logo' className={styles.loginLogo} src='/fruitiionBannerLogoWhite.png' width={303} height={106} priority/>
   
          <p className={styles.forgotPasswordLink}>Thank you for using Fruitiion. <br/><br/> Currently we do not support mobile devices.<br /> <br/>If you are not using a mobile device and see this page, please email info@fruitiion.com</p>
        </div>
      </div>
      {
        isLoading ?
        <FlowLoader />:
        null
      }
      <Footer />
    </div>
  )
}
